from mcmxi_sopel_modules.cottongin.sopel_modules.exchange import *
from mcmxi_sopel_modules.cottongin.sopel_modules.figlet import *
#from mcmxi_sopel_modules.cottongin.sopel_modules.food import *
from mcmxi_sopel_modules.cottongin.sopel_modules.gas import *
from mcmxi_sopel_modules.cottongin.sopel_modules.hueg import *
#from mcmxi_sopel_modules.cottongin.sopel_modules.imgur import *
from mcmxi_sopel_modules.cottongin.sopel_modules.misc import *
#from mcmxi_sopel_modules.cottongin.sopel_modules.mma import *
from mcmxi_sopel_modules.cottongin.sopel_modules.nhl import *
from mcmxi_sopel_modules.cottongin.sopel_modules.odds import *
from mcmxi_sopel_modules.cottongin.sopel_modules.podcasts import *
#from mcmxi_sopel_modules.cottongin.sopel_modules.reelgoodroulette import *
from mcmxi_sopel_modules.cottongin.sopel_modules.soma import *
from mcmxi_sopel_modules.cottongin.sopel_modules.space import *
from mcmxi_sopel_modules.cottongin.sopel_modules.spongebob import *
#from mcmxi_sopel_modules.cottongin.sopel_modules.steam import *
from mcmxi_sopel_modules.cottongin.sopel_modules.twitch import *
from mcmxi_sopel_modules.cottongin.sopel_modules.twitter import *
from mcmxi_sopel_modules.cottongin.sopel_modules.urbandictionary import *
from mcmxi_sopel_modules.cottongin.sopel_modules.vimeo import *
from mcmxi_sopel_modules.cottongin.sopel_modules.wolfram import *

from mcmxi_sopel_modules.dasu.syrup_sopel_modules.anilist import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.anime import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.animerss import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.bday import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.bitcoin import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.dubtrack import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.edict import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.egs import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.fact import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.gdq import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.gelbooru import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.heh import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.hltb import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.hn import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.hots import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.instagram import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.jeopardy import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.knowyourmeme import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.mahjong import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.mal import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.mtg import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.nicovideourl import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.pb import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.pixiv import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.ps import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.ratewaifu import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.remind import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.search2 import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.shadowverse import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.smug import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.sotd import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.soundcloudurl import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.ssthis import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.steam import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.stocks import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.sync import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.testmods import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.traffic import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.trivia import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.twitch import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.twitter import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.urbandict import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.url2 import *
#from mcmxi_sopel_modules.dasu.syrup_sopel_modules.vndb import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.wafflebot import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.wait import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.weather2 import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.wemo import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.worldcup import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.ygo import *
from mcmxi_sopel_modules.dasu.syrup_sopel_modules.youtoob import *

from mcmxi_sopel_modules.jinpark.phenny_modules.aftership import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.air-quality import *
from mcmxi_sopel_modules.jinpark.phenny_modules.alphavantage import *
from mcmxi_sopel_modules.jinpark.phenny_modules.bobkov import *
from mcmxi_sopel_modules.jinpark.phenny_modules.crypto import *
from mcmxi_sopel_modules.jinpark.phenny_modules.giphy import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.google_search import *
from mcmxi_sopel_modules.jinpark.phenny_modules.jargon import *
from mcmxi_sopel_modules.jinpark.phenny_modules.jisho import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.new-clock import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.new-translate import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.new-url import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.new-weather import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.new-wikipedia import *
from mcmxi_sopel_modules.jinpark.phenny_modules.stocks import *
from mcmxi_sopel_modules.jinpark.phenny_modules.urbandictionary import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.visualcrossing import *
from mcmxi_sopel_modules.jinpark.phenny_modules.voice_join import *
#from mcmxi_sopel_modules.jinpark.phenny_modules.wolfram import *
